Repository hmcts/ccpay-scheduled-jobs, pull requests merged in 2024-05, with the labels that each got.

#104 Add nightly pipeline
  Jenkinsfile_nightly
  config/owasp/suppressions.xml
Labels: ns:fees-pay, prd:payment, rel:payment-jobs-pr-104

#103 PAY-6296: Fix CVE-2022-1471
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:fees-pay, prd:payment, rel:payment-jobs-pr-103

#109 Enable App Insights
  Dockerfile
  build.gradle
Labels: ns:fees-pay, prd:payment, rel:payment-jobs-pr-109

#108 PAY-7109: Correct app-insight
  Dockerfile
  build.gradle
  charts/payment-jobs/Chart.yaml
  charts/payment-jobs/values.yaml
  config/owasp/suppressions.xml
  lib/applicationinsights.json
Labels: ns:fees-pay, prd:payment, rel:payment-jobs-pr-108

#110 Fix secret ref
  charts/payment-jobs/Chart.yaml
  charts/payment-jobs/values.yaml
Labels: ns:fees-pay, prd:payment, rel:payment-jobs-pr-110

#111 PAY-6820: Adding Specified Money Claims to PBA Report
  charts/payment-jobs/Chart.yaml
  docker-compose.yml
  src/main/java/uk/gov/hmcts/payment/processors/PbaCsvReportProcessor.java
Labels: ns:fees-pay, prd:payment, rel:payment-jobs-pr-111

#112 PAY-7124: Address High Vulnerabilities
  build.gradle
  config/owasp/suppressions.xml
  cve-resolution-strategy.gradle
Labels: ns:fees-pay, prd:payment, rel:payment-jobs-pr-112
