Repository hmcts/ccpay-scheduled-jobs, pull requests merged in 2024-07, with the labels that each got.

#125 Revert "Update plugin org.owasp.dependencycheck to v10"
  build.gradle
Labels: ns:fees-pay, prd:payment, rel:payment-jobs-pr-125

#124 PAY-7231: Revert owasp library to fix pipeline
  build.gradle
Labels: ns:fees-pay, prd:payment, rel:payment-jobs-pr-124

#129 PAY-7244: Update to use available groovy-xml lib
  build.gradle
Labels: ns:fees-pay, prd:payment, rel:payment-jobs-pr-129
