Repository hmcts/ccpay-scheduled-jobs, pull requests merged in 2025-07, with the labels that each got.

#205 CME-529 replace jitpack with azure
  build.gradle
  jitpack.yml
Labels: ns:fees-pay, prd:payment, rel:payment-jobs-pr-205

#206 PAY-7544 upgrade commons-io
  build.gradle
  cve-resolution-strategy.gradle
Labels: ns:fees-pay, prd:payment, rel:payment-jobs-pr-206

#208 Address CVE-2025-48976
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:fees-pay, prd:payment, rel:payment-jobs-pr-208

#212 PAY-7984 commons-lang3 cve
  build.gradle
Labels: ns:fees-pay, prd:payment, rel:payment-jobs-pr-212
